"""update_user

Revision ID: 7de9af8bb80e
Revises: 3f9d5c008459
Create Date: 2023-08-10 20:52:03.330592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de9af8bb80e'
down_revision: Union[str, None] = '3f9d5c008459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tracker', sa.Column('hashed_password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tracker', 'hashed_password')
    # ### end Alembic commands ###
